### ISSUE TITLE
Can't close or write jpeg file

### ISSUE THREAD

**Issue by lewisl** [python-xmp-toolkit/python-xmp-toolkit#57] opened 2016-05-06 20:48 UTC
I've encountered a strange problem.  exempi can't close a jpeg file.  It is one of several very similar files in the same directory.  You'd suspect a permissions problem but other files in the same directory can be written.  It could be a malformed jpeg for some reason or with bad embedded metadata.  But the mac app called photo meta edit.app can edit and create xmp fields and successfully write and close the file.

But exempi can't.  Here is the error message:

`LFA_OpenRsrc: open failure`

I have run through Python debugger.  All of the following statements conclude successfully:

```
xmp = xmpfile.get_xmp()
xmp.set_property(namespace, attr, value)
xmpfile.put_xmp(xmp)
```

The code fails at:

```
xmpfile.close_file()
```

Below I post the python function where I update and write the jpeg file. Also, the state of the xmp metadata as modified by the code.  It looks like clean metadata, but maybe I am missing something.

All I can think is there is something just off about the file size so that there is some awkward word boundary that hangs up exempi.

Sorry for the long post.  Just wanted to include what I could to help figure this out.

Here is my function:

```
def put_pic_metadata(fname, changes):
    """Write xmp metadata into an image file.  Requires Python XMP Library."""

    result = True   # unless failure or exception, below
    if changes:
        try:
            xmpfile = XMPFiles(file_path=fname, open_forupdate=True)
            xmp = xmpfile.get_xmp()  # load metadata as python dict of arrays
            for item in changes:
                prefix, attr = item[0].split(":")  # assign the 2 pieces
                namespace = xmp_namespaces[prefix]  # expand to url of namespace
                value = item[1]
                if xmpfile.can_put_xmp(xmp):
                    try:
                        if isinstance(value, int):
                            xmp.set_property_int(namespace, attr, value)
                        elif isinstance(value, bool):
                            xmp.set_property_bool(namespace, attr, value)
                        else:
                            xmp.set_property(namespace, attr, value)

                        xmpfile.put_xmp(xmp)  # write it to disk
                    except (TypeError, IOError):
                        print(item)
                        print(sys.exc_info()[0], "Failed to write", fname)
                        result = False  # Failure
                else:
                    result = False  # failure
            xmpfile.close_file()
        except:   # untrappable errors from libxmp
            print("Could not open, write, or close:", fname)
            result = False

    return result

```

Here is the xml:

```
<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Exempi + XMP Core 5.1.2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
   <photoshop:DateCreated>2016-04-11T13:52:12-07:00</photoshop:DateCreated>
   <photoshop:Instructions>C1 Edits</photoshop:Instructions>
  </rdf:Description>
  <rdf:Description rdf:about=""
    xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
   <tiff:Orientation>1</tiff:Orientation>
   <tiff:YCbCrPositioning>2</tiff:YCbCrPositioning>
   <tiff:XResolution>350/1</tiff:XResolution>
   <tiff:YResolution>350/1</tiff:YResolution>
   <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
   <tiff:Make>SONY</tiff:Make>
   <tiff:Model>DSC-RX100M4</tiff:Model>
  </rdf:Description>
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/">
   <xmp:CreatorTool>DSC-RX100M4 v1.20</xmp:CreatorTool>
   <xmp:ModifyDate>2016-04-11T13:52:12</xmp:ModifyDate>
   <xmp:CreateDate>2016-04-11T13:52:12</xmp:CreateDate>
  </rdf:Description>
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/">
   <exif:ColorSpace>1</exif:ColorSpace>
   <exif:CompressedBitsPerPixel>5/1</exif:CompressedBitsPerPixel>
   <exif:PixelXDimension>4864</exif:PixelXDimension>
   <exif:PixelYDimension>3648</exif:PixelYDimension>
   <exif:ExposureTime>1/800</exif:ExposureTime>
   <exif:FNumber>56/10</exif:FNumber>
   <exif:ExposureProgram>2</exif:ExposureProgram>
   <exif:BrightnessValue>28934/2560</exif:BrightnessValue>
   <exif:ExposureBiasValue>0/10</exif:ExposureBiasValue>
   <exif:MaxApertureValue>434/256</exif:MaxApertureValue>
   <exif:MeteringMode>5</exif:MeteringMode>
   <exif:LightSource>0</exif:LightSource>
   <exif:FocalLength>880/100</exif:FocalLength>
   <exif:CustomRendered>0</exif:CustomRendered>
   <exif:ExposureMode>0</exif:ExposureMode>
   <exif:WhiteBalance>0</exif:WhiteBalance>
   <exif:DigitalZoomRatio>16/16</exif:DigitalZoomRatio>
   <exif:FocalLengthIn35mmFilm>24</exif:FocalLengthIn35mmFilm>
   <exif:SceneCaptureType>0</exif:SceneCaptureType>
   <exif:Contrast>0</exif:Contrast>
   <exif:Saturation>0</exif:Saturation>
   <exif:Sharpness>0</exif:Sharpness>
   <exif:DateTimeOriginal>2016-04-11T13:52:12</exif:DateTimeOriginal>
   <exif:ISOSpeedRatings>
    <rdf:Seq>
     <rdf:li>125</rdf:li>
    </rdf:Seq>
   </exif:ISOSpeedRatings>
   <exif:ExifVersion>0230</exif:ExifVersion>
   <exif:FlashpixVersion>0100</exif:FlashpixVersion>
   <exif:ComponentsConfiguration>
    <rdf:Seq>
     <rdf:li>1</rdf:li>
     <rdf:li>2</rdf:li>
     <rdf:li>3</rdf:li>
     <rdf:li>0</rdf:li>
    </rdf:Seq>
   </exif:ComponentsConfiguration>
   <exif:Flash rdf:parseType="Resource">
    <exif:Fired>False</exif:Fired>
    <exif:Return>0</exif:Return>
    <exif:Mode>2</exif:Mode>
    <exif:Function>False</exif:Function>
    <exif:RedEyeMode>False</exif:RedEyeMode>
   </exif:Flash>
   <exif:FileSource>3</exif:FileSource>
   <exif:SceneType>1</exif:SceneType>
  </rdf:Description>
  <rdf:Description rdf:about=""
    xmlns:dc="http://purl.org/dc/elements/1.1/">
   <dc:creator>
    <rdf:Seq>
     <rdf:li>lewis c levin</rdf:li>
    </rdf:Seq>
   </dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
```

**Comment by quintusdias** [comment] 2016-05-11 23:50
Hi, I apologize for the lateness in my response, any chance I could get my
hands on the JPEG file in question?

On Fri, May 6, 2016 at 4:48 PM, lewisl <notifications@github.com> wrote:

> I've encountered a strange problem. exempi can't close a jpeg file. It is
> one of several very similar files in the same directory. You'd suspect a
> permissions problem but other files in the same directory can be written.
> It could be a malformed jpeg for some reason or with bad embedded metadata.
> But the mac app called photo meta edit.app can edit and create xmp fields
> and successfully write and close the file.
>
> But exempi can't. Here is the error message:
>
> LFA_OpenRsrc: open failure
>
> I have run through Python debugger. All of the following statements
> conclude successfully:
>
> xmp = xmpfile.get_xmp()
> xmp.set_property(namespace, attr, value)
> xmpfile.put_xmp(xmp)
>
> The code fails at:
>
> xmpfile.close_file()
>
> Below I post the python function where I update and write the jpeg file.
> Also, the state of the xmp metadata as modified by the code. It looks like
> clean metadata, but maybe I am missing something.
>
> All I can think is there is something just off about the file size so that
> there is some awkward word boundary that hangs up exempi.
>
> Sorry for the long post. Just wanted to include what I could to help
> figure this out.
>
> Here is my function:
>
> def put_pic_metadata(fname, changes):
>     """Write xmp metadata into an image file.  Requires Python XMP Library."""
>
>     result = True   # unless failure or exception, below
>     if changes:
>         try:
>             xmpfile = XMPFiles(file_path=fname, open_forupdate=True)
>             xmp = xmpfile.get_xmp()  # load metadata as python dict of arrays
>             for item in changes:
>                 prefix, attr = item[0].split(":")  # assign the 2 pieces
>                 namespace = xmp_namespaces[prefix]  # expand to url of namespace
>                 value = item[1]
>                 if xmpfile.can_put_xmp(xmp):
>                     try:
>                         if isinstance(value, int):
>                             xmp.set_property_int(namespace, attr, value)
>                         elif isinstance(value, bool):
>                             xmp.set_property_bool(namespace, attr, value)
>                         else:
>                             xmp.set_property(namespace, attr, value)
>
>                         xmpfile.put_xmp(xmp)  # write it to disk
>                     except (TypeError, IOError):
>                         print(item)
>                         print(sys.exc_info()[0], "Failed to write", fname)
>                         result = False  # Failure
>                 else:
>                     result = False  # failure
>             xmpfile.close_file()
>         except:   # untrappable errors from libxmp
>             print("Could not open, write, or close:", fname)
>             result = False
>
>     return result
>
>
> Here is the xml:
>
> <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Exempi + XMP Core 5.1.2">
>  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
>   <rdf:Description rdf:about=""
>     xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
>    <photoshop:DateCreated>2016-04-11T13:52:12-07:00</photoshop:DateCreated>
>    <photoshop:Instructions>C1 Edits</photoshop:Instructions>
>   </rdf:Description>
>   <rdf:Description rdf:about=""
>     xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
>    <tiff:Orientation>1</tiff:Orientation>
>    <tiff:YCbCrPositioning>2</tiff:YCbCrPositioning>
>    <tiff:XResolution>350/1</tiff:XResolution>
>    <tiff:YResolution>350/1</tiff:YResolution>
>    <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
>    <tiff:Make>SONY</tiff:Make>
>    <tiff:Model>DSC-RX100M4</tiff:Model>
>   </rdf:Description>
>   <rdf:Description rdf:about=""
>     xmlns:xmp="http://ns.adobe.com/xap/1.0/">
>    <xmp:CreatorTool>DSC-RX100M4 v1.20</xmp:CreatorTool>
>    <xmp:ModifyDate>2016-04-11T13:52:12</xmp:ModifyDate>
>    <xmp:CreateDate>2016-04-11T13:52:12</xmp:CreateDate>
>   </rdf:Description>
>   <rdf:Description rdf:about=""
>     xmlns:exif="http://ns.adobe.com/exif/1.0/">
>    <exif:ColorSpace>1</exif:ColorSpace>
>    <exif:CompressedBitsPerPixel>5/1</exif:CompressedBitsPerPixel>
>    <exif:PixelXDimension>4864</exif:PixelXDimension>
>    <exif:PixelYDimension>3648</exif:PixelYDimension>
>    <exif:ExposureTime>1/800</exif:ExposureTime>
>    <exif:FNumber>56/10</exif:FNumber>
>    <exif:ExposureProgram>2</exif:ExposureProgram>
>    <exif:BrightnessValue>28934/2560</exif:BrightnessValue>
>    <exif:ExposureBiasValue>0/10</exif:ExposureBiasValue>
>    <exif:MaxApertureValue>434/256</exif:MaxApertureValue>
>    <exif:MeteringMode>5</exif:MeteringMode>
>    <exif:LightSource>0</exif:LightSource>
>    <exif:FocalLength>880/100</exif:FocalLength>
>    <exif:CustomRendered>0</exif:CustomRendered>
>    <exif:ExposureMode>0</exif:ExposureMode>
>    <exif:WhiteBalance>0</exif:WhiteBalance>
>    <exif:DigitalZoomRatio>16/16</exif:DigitalZoomRatio>
>    <exif:FocalLengthIn35mmFilm>24</exif:FocalLengthIn35mmFilm>
>    <exif:SceneCaptureType>0</exif:SceneCaptureType>
>    <exif:Contrast>0</exif:Contrast>
>    <exif:Saturation>0</exif:Saturation>
>    <exif:Sharpness>0</exif:Sharpness>
>    <exif:DateTimeOriginal>2016-04-11T13:52:12</exif:DateTimeOriginal>
>    <exif:ISOSpeedRatings>
>     <rdf:Seq>
>      <rdf:li>125</rdf:li>
>     </rdf:Seq>
>    </exif:ISOSpeedRatings>
>    <exif:ExifVersion>0230</exif:ExifVersion>
>    <exif:FlashpixVersion>0100</exif:FlashpixVersion>
>    <exif:ComponentsConfiguration>
>     <rdf:Seq>
>      <rdf:li>1</rdf:li>
>      <rdf:li>2</rdf:li>
>      <rdf:li>3</rdf:li>
>      <rdf:li>0</rdf:li>
>     </rdf:Seq>
>    </exif:ComponentsConfiguration>
>    <exif:Flash rdf:parseType="Resource">
>     <exif:Fired>False</exif:Fired>
>     <exif:Return>0</exif:Return>
>     <exif:Mode>2</exif:Mode>
>     <exif:Function>False</exif:Function>
>     <exif:RedEyeMode>False</exif:RedEyeMode>
>    </exif:Flash>
>    <exif:FileSource>3</exif:FileSource>
>    <exif:SceneType>1</exif:SceneType>
>   </rdf:Description>
>   <rdf:Description rdf:about=""
>     xmlns:dc="http://purl.org/dc/elements/1.1/">
>    <dc:creator>
>     <rdf:Seq>
>      <rdf:li>lewis c levin</rdf:li>
>     </rdf:Seq>
>    </dc:creator>
>   </rdf:Description>
>  </rdf:RDF>
> </x:xmpmeta>
> <?xpacket end="w"?>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/57>
>



-- 
John Evans

**Comment by lewisl** [comment] 2016-05-12 01:11
I am embarrassed to say I can’t repro it now.  I had made a copy of the errant file and at the time both the original and the copy produced the message.  I only edited the original with Photo Meta Edit so that could have only fixed the original.  Now, it all works (even after editing the xmp data and writing changes with an image editor.

So, nothing for now.

But, a related question:  I looked at the source code to see where you raise libxmp python conditions.  I can see the naming for the module but when I import it I don’t pick up the conditions.  So, I am unable to trap the specific conditions that can occur in libxmp or exempi (I suppose only the Python wrapper).

Thanks for the reply.

Lewis


On May 11, 2016, at 4:50 PM, John G Evans <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, I apologize for the lateness in my response, any chance I could get my
hands on the JPEG file in question?

On Fri, May 6, 2016 at 4:48 PM, lewisl <notifications@github.com<mailto:notifications@github.com>> wrote:

> I've encountered a strange problem. exempi can't close a jpeg file. It is
> one of several very similar files in the same directory. You'd suspect a
> permissions problem but other files in the same directory can be written.
> It could be a malformed jpeg for some reason or with bad embedded metadata.
> But the mac app called photo meta edit.app can edit and create xmp fields
> and successfully write and close the file.
>
> But exempi can't. Here is the error message:
>
> LFA_OpenRsrc: open failure
>
> I have run through Python debugger. All of the following statements
> conclude successfully:
>
> xmp = xmpfile.get_xmp()
> xmp.set_property(namespace, attr, value)
> xmpfile.put_xmp(xmp)
>
> The code fails at:
>
> xmpfile.close_file()
>
> Below I post the python function where I update and write the jpeg file.
> Also, the state of the xmp metadata as modified by the code. It looks like
> clean metadata, but maybe I am missing something.
>
> All I can think is there is something just off about the file size so that
> there is some awkward word boundary that hangs up exempi.
>
> Sorry for the long post. Just wanted to include what I could to help
> figure this out.
>
> Here is my function:
>
> def put_pic_metadata(fname, changes):
> """Write xmp metadata into an image file. Requires Python XMP Library."""
>
> result = True # unless failure or exception, below
> if changes:
> try:
> xmpfile = XMPFiles(file_path=fname, open_forupdate=True)
> xmp = xmpfile.get_xmp() # load metadata as python dict of arrays
> for item in changes:
> prefix, attr = item[0].split(":") # assign the 2 pieces
> namespace = xmp_namespaces[prefix] # expand to url of namespace
> value = item[1]
> if xmpfile.can_put_xmp(xmp):
> try:
> if isinstance(value, int):
> xmp.set_property_int(namespace, attr, value)
> elif isinstance(value, bool):
> xmp.set_property_bool(namespace, attr, value)
> else:
> xmp.set_property(namespace, attr, value)
>
> xmpfile.put_xmp(xmp) # write it to disk
> except (TypeError, IOError):
> print(item)
> print(sys.exc_info()[0], "Failed to write", fname)
> result = False # Failure
> else:
> result = False # failure
> xmpfile.close_file()
> except: # untrappable errors from libxmp
> print("Could not open, write, or close:", fname)
> result = False
>
> return result
>
>
> Here is the xml:
>
> <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Exempi + XMP Core 5.1.2">
> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
> <rdf:Description rdf:about=""
> xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
> <photoshop:DateCreated>2016-04-11T13:52:12-07:00</photoshop:DateCreated>
> <photoshop:Instructions>C1 Edits</photoshop:Instructions>
> </rdf:Description>
> <rdf:Description rdf:about=""
> xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
> <tiff:Orientation>1</tiff:Orientation>
> <tiff:YCbCrPositioning>2</tiff:YCbCrPositioning>
> <tiff:XResolution>350/1</tiff:XResolution>
> <tiff:YResolution>350/1</tiff:YResolution>
> <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
> <tiff:Make>SONY</tiff:Make>
> <tiff:Model>DSC-RX100M4</tiff:Model>
> </rdf:Description>
> <rdf:Description rdf:about=""
> xmlns:xmp="http://ns.adobe.com/xap/1.0/">
> <xmp:CreatorTool>DSC-RX100M4 v1.20</xmp:CreatorTool>
> <xmp:ModifyDate>2016-04-11T13:52:12</xmp:ModifyDate>
> <xmp:CreateDate>2016-04-11T13:52:12</xmp:CreateDate>
> </rdf:Description>
> <rdf:Description rdf:about=""
> xmlns:exif="http://ns.adobe.com/exif/1.0/">
> <exif:ColorSpace>1</exif:ColorSpace>
> <exif:CompressedBitsPerPixel>5/1</exif:CompressedBitsPerPixel>
> <exif:PixelXDimension>4864</exif:PixelXDimension>
> <exif:PixelYDimension>3648</exif:PixelYDimension>
> <exif:ExposureTime>1/800</exif:ExposureTime>
> <exif:FNumber>56/10</exif:FNumber>
> <exif:ExposureProgram>2</exif:ExposureProgram>
> <exif:BrightnessValue>28934/2560</exif:BrightnessValue>
> <exif:ExposureBiasValue>0/10</exif:ExposureBiasValue>
> <exif:MaxApertureValue>434/256</exif:MaxApertureValue>
> <exif:MeteringMode>5</exif:MeteringMode>
> <exif:LightSource>0</exif:LightSource>
> <exif:FocalLength>880/100</exif:FocalLength>
> <exif:CustomRendered>0</exif:CustomRendered>
> <exif:ExposureMode>0</exif:ExposureMode>
> <exif:WhiteBalance>0</exif:WhiteBalance>
> <exif:DigitalZoomRatio>16/16</exif:DigitalZoomRatio>
> <exif:FocalLengthIn35mmFilm>24</exif:FocalLengthIn35mmFilm>
> <exif:SceneCaptureType>0</exif:SceneCaptureType>
> <exif:Contrast>0</exif:Contrast>
> <exif:Saturation>0</exif:Saturation>
> <exif:Sharpness>0</exif:Sharpness>
> <exif:DateTimeOriginal>2016-04-11T13:52:12</exif:DateTimeOriginal>
> <exif:ISOSpeedRatings>
> <rdf:Seq>
> <rdf:li>125</rdf:li>
> </rdf:Seq>
> </exif:ISOSpeedRatings>
> <exif:ExifVersion>0230</exif:ExifVersion>
> <exif:FlashpixVersion>0100</exif:FlashpixVersion>
> <exif:ComponentsConfiguration>
> <rdf:Seq>
> <rdf:li>1</rdf:li>
> <rdf:li>2</rdf:li>
> <rdf:li>3</rdf:li>
> <rdf:li>0</rdf:li>
> </rdf:Seq>
> </exif:ComponentsConfiguration>
> <exif:Flash rdf:parseType="Resource">
> <exif:Fired>False</exif:Fired>
> <exif:Return>0</exif:Return>
> <exif:Mode>2</exif:Mode>
> <exif:Function>False</exif:Function>
> <exif:RedEyeMode>False</exif:RedEyeMode>
> </exif:Flash>
> <exif:FileSource>3</exif:FileSource>
> <exif:SceneType>1</exif:SceneType>
> </rdf:Description>
> <rdf:Description rdf:about=""
> xmlns:dc="http://purl.org/dc/elements/1.1/">
> <dc:creator>
> <rdf:Seq>
> <rdf:li>lewis c levin</rdf:li>
> </rdf:Seq>
> </dc:creator>
> </rdf:Description>
> </rdf:RDF>
> </x:xmpmeta>
> <?xpacket end="w"?>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/57>
>



--
John Evans

**Comment by quintusdias** [comment] 2016-05-14 22:40
You may be seeing messages raised by the exempi library itself, e.g. the
message you originally mention, ``LFA_OpenRsrc``` is raised by the
libexempi library.

On Wed, May 11, 2016 at 9:11 PM, lewisl <notifications@github.com> wrote:

> I am embarrassed to say I can’t repro it now. I had made a copy of the
> errant file and at the time both the original and the copy produced the
> message. I only edited the original with Photo Meta Edit so that could have
> only fixed the original. Now, it all works (even after editing the xmp data
> and writing changes with an image editor.
>
> So, nothing for now.
>
> But, a related question: I looked at the source code to see where you
> raise libxmp python conditions. I can see the naming for the module but
> when I import it I don’t pick up the conditions. So, I am unable to trap
> the specific conditions that can occur in libxmp or exempi (I suppose only
> the Python wrapper).
>
> Thanks for the reply.
>
> Lewis
>
>
> On May 11, 2016, at 4:50 PM, John G Evans <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
> Hi, I apologize for the lateness in my response, any chance I could get my
> hands on the JPEG file in question?
>
> On Fri, May 6, 2016 at 4:48 PM, lewisl <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> > I've encountered a strange problem. exempi can't close a jpeg file. It
> is
> > one of several very similar files in the same directory. You'd suspect a
> > permissions problem but other files in the same directory can be
> written.
> > It could be a malformed jpeg for some reason or with bad embedded
> metadata.
> > But the mac app called photo meta edit.app can edit and create xmp
> fields
> > and successfully write and close the file.
> >
> > But exempi can't. Here is the error message:
> >
> > LFA_OpenRsrc: open failure
> >
> > I have run through Python debugger. All of the following statements
> > conclude successfully:
> >
> > xmp = xmpfile.get_xmp()
> > xmp.set_property(namespace, attr, value)
> > xmpfile.put_xmp(xmp)
> >
> > The code fails at:
> >
> > xmpfile.close_file()
> >
> > Below I post the python function where I update and write the jpeg file.
> > Also, the state of the xmp metadata as modified by the code. It looks
> like
> > clean metadata, but maybe I am missing something.
> >
> > All I can think is there is something just off about the file size so
> that
> > there is some awkward word boundary that hangs up exempi.
> >
> > Sorry for the long post. Just wanted to include what I could to help
> > figure this out.
> >
> > Here is my function:
> >
> > def put_pic_metadata(fname, changes):
> > """Write xmp metadata into an image file. Requires Python XMP
> Library."""
> >
> > result = True # unless failure or exception, below
> > if changes:
> > try:
> > xmpfile = XMPFiles(file_path=fname, open_forupdate=True)
> > xmp = xmpfile.get_xmp() # load metadata as python dict of arrays
> > for item in changes:
> > prefix, attr = item[0].split(":") # assign the 2 pieces
> > namespace = xmp_namespaces[prefix] # expand to url of namespace
> > value = item[1]
> > if xmpfile.can_put_xmp(xmp):
> > try:
> > if isinstance(value, int):
> > xmp.set_property_int(namespace, attr, value)
> > elif isinstance(value, bool):
> > xmp.set_property_bool(namespace, attr, value)
> > else:
> > xmp.set_property(namespace, attr, value)
> >
> > xmpfile.put_xmp(xmp) # write it to disk
> > except (TypeError, IOError):
> > print(item)
> > print(sys.exc_info()[0], "Failed to write", fname)
> > result = False # Failure
> > else:
> > result = False # failure
> > xmpfile.close_file()
> > except: # untrappable errors from libxmp
> > print("Could not open, write, or close:", fname)
> > result = False
> >
> > return result
> >
> >
> > Here is the xml:
> >
> > <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
> > <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Exempi + XMP Core 5.1.2">
> > <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
> > <rdf:Description rdf:about=""
> > xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
> > <photoshop:DateCreated>2016-04-11T13:52:12-07:00</photoshop:DateCreated>
> > <photoshop:Instructions>C1 Edits</photoshop:Instructions>
> > </rdf:Description>
> > <rdf:Description rdf:about=""
> > xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
> > <tiff:Orientation>1</tiff:Orientation>
> > <tiff:YCbCrPositioning>2</tiff:YCbCrPositioning>
> > <tiff:XResolution>350/1</tiff:XResolution>
> > <tiff:YResolution>350/1</tiff:YResolution>
> > <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
> > <tiff:Make>SONY</tiff:Make>
> > <tiff:Model>DSC-RX100M4</tiff:Model>
> > </rdf:Description>
> > <rdf:Description rdf:about=""
> > xmlns:xmp="http://ns.adobe.com/xap/1.0/">
> > <xmp:CreatorTool>DSC-RX100M4 v1.20</xmp:CreatorTool>
> > <xmp:ModifyDate>2016-04-11T13:52:12</xmp:ModifyDate>
> > <xmp:CreateDate>2016-04-11T13:52:12</xmp:CreateDate>
> > </rdf:Description>
> > <rdf:Description rdf:about=""
> > xmlns:exif="http://ns.adobe.com/exif/1.0/">
> > <exif:ColorSpace>1</exif:ColorSpace>
> > <exif:CompressedBitsPerPixel>5/1</exif:CompressedBitsPerPixel>
> > <exif:PixelXDimension>4864</exif:PixelXDimension>
> > <exif:PixelYDimension>3648</exif:PixelYDimension>
> > <exif:ExposureTime>1/800</exif:ExposureTime>
> > <exif:FNumber>56/10</exif:FNumber>
> > <exif:ExposureProgram>2</exif:ExposureProgram>
> > <exif:BrightnessValue>28934/2560</exif:BrightnessValue>
> > <exif:ExposureBiasValue>0/10</exif:ExposureBiasValue>
> > <exif:MaxApertureValue>434/256</exif:MaxApertureValue>
> > <exif:MeteringMode>5</exif:MeteringMode>
> > <exif:LightSource>0</exif:LightSource>
> > <exif:FocalLength>880/100</exif:FocalLength>
> > <exif:CustomRendered>0</exif:CustomRendered>
> > <exif:ExposureMode>0</exif:ExposureMode>
> > <exif:WhiteBalance>0</exif:WhiteBalance>
> > <exif:DigitalZoomRatio>16/16</exif:DigitalZoomRatio>
> > <exif:FocalLengthIn35mmFilm>24</exif:FocalLengthIn35mmFilm>
> > <exif:SceneCaptureType>0</exif:SceneCaptureType>
> > <exif:Contrast>0</exif:Contrast>
> > <exif:Saturation>0</exif:Saturation>
> > <exif:Sharpness>0</exif:Sharpness>
> > <exif:DateTimeOriginal>2016-04-11T13:52:12</exif:DateTimeOriginal>
> > <exif:ISOSpeedRatings>
> > <rdf:Seq>
> > <rdf:li>125</rdf:li>
> > </rdf:Seq>
> > </exif:ISOSpeedRatings>
> > <exif:ExifVersion>0230</exif:ExifVersion>
> > <exif:FlashpixVersion>0100</exif:FlashpixVersion>
> > <exif:ComponentsConfiguration>
> > <rdf:Seq>
> > <rdf:li>1</rdf:li>
> > <rdf:li>2</rdf:li>
> > <rdf:li>3</rdf:li>
> > <rdf:li>0</rdf:li>
> > </rdf:Seq>
> > </exif:ComponentsConfiguration>
> > <exif:Flash rdf:parseType="Resource">
> > <exif:Fired>False</exif:Fired>
> > <exif:Return>0</exif:Return>
> > <exif:Mode>2</exif:Mode>
> > <exif:Function>False</exif:Function>
> > <exif:RedEyeMode>False</exif:RedEyeMode>
> > </exif:Flash>
> > <exif:FileSource>3</exif:FileSource>
> > <exif:SceneType>1</exif:SceneType>
> > </rdf:Description>
> > <rdf:Description rdf:about=""
> > xmlns:dc="http://purl.org/dc/elements/1.1/">
> > <dc:creator>
> > <rdf:Seq>
> > <rdf:li>lewis c levin</rdf:li>
> > </rdf:Seq>
> > </dc:creator>
> > </rdf:Description>
> > </rdf:RDF>
> > </x:xmpmeta>
> > <?xpacket end="w"?>
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/57>
> >
>
>
>
> --
> John Evans
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/57#issuecomment-218623221>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/57#issuecomment-218634083>
>



-- 
John Evans

**Comment by zougloub** [comment] 2024-01-08 16:03
Closing due to age and reproducibility issues, @lewisl please feel free to reopen with additional information that would help reproduce the issue.

**Closed by zougloub** 2024-01-08 16:03 UTC
